services:
  frontend:
    build:
      context: ./frontend

    working_dir: /workspace/frontend

    volumes:
      - ./frontend:/workspace/frontend
      - frontend_node_modules:/workspace/frontend/node_modules

    ports:
      - "5173:5173"

    command:
      npm run dev -- --host

    depends_on:
      - backend


  backend:
    build:
      context: ./backend

    working_dir: /workspace/backend

    volumes:
      - ./backend:/workspace/backend
      - backend_venv:/workspace/backend/.venv

    ports:
      - "8000:8000"

    command:
      uv run uvicorn app.main:app --host 0.0.0.0 --reload


  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - .:/workspace
      - frontend_node_modules:/workspace/frontend/node_modules
      - backend_venv:/workspace/backend/.venv

    working_dir: /workspace

    command:
      sleep infinity


volumes:
  frontend_node_modules:
  backend_venv: